### ISSUE TITLE
attempt_stats_request limited to 100 results

### ISSUE THREAD

**Issue by jiahao** [WestleyArgentum/GitHub.jl#23]
The stats URI appears to be hard limited to 100 results and therefore it is not possible to retrieve more than 100 contributors, stargazers, etc. Specifying the additional query "?pages=2" does not change the results, as would be expected from the [pagination section of the API](https://developer.github.com/v3/#pagination)

**Comment by WestleyArgentum** [comment]
That's weird, I'm able to get full lists for both contributors and stargazers:
```
julia> stargazers("julialang", "julia", auth = a)
5107-element Array{User,1}:
 User - brixen
 User - daksis
 User - willcodeforfoo
 User - lancecarlson
 User - DocSavage
 User - brapse
 User - vic
 User - sbusso
 User - raggi
 User - methodmissing
 User - brainopia
 User - jarkko
 User - auser
 User - jarib
 ⋮
 User - paegun
 User - usptact
 User - markdjthomas
 User - zhengxwen
 User - tpapp
 User - hellerve
 User - 315234
 User - SimonDanisch
 User - wxia
 User - hibiu1
 User - shyam057cs
 User - twolodzko
 User - jsbee
```

Maybe the problem is with unauthenticated requests? Unfortunately I can't test here, unauthenticated requests from my ip address are being blocked by github for some reason...

**Comment by WestleyArgentum** [comment]
Oh, it has been so long since I've looked at this, totally forgot about https://github.com/WestleyArgentum/GitHub.jl/blob/master/src/utils.jl#L53

So `stargazers`, `contributors`, etc, should be making the repeated requests for you (and I'm not being blocked by github, I'm making too many calls haha).

**Comment by WestleyArgentum** [comment]
Sorry for totally narrating the debugging process, realized that you had `attempt_stats_request` in the title and that my list of contributors was in fact truncated. Looks like we need to work `get_pages` into stats requests

**Comment by WestleyArgentum** [comment]
Alas! I refactored this to support paging, only to discover that github doesn't do paging for contributors because it's too expensive an operation: https://stackoverflow.com/questions/18148490/how-can-i-get-more-than-100-results-from-github-api-v3-using-github-api-gem

So I guess this is as fixed as I can make it -- if github ever flips the switch and turns on paging for contributors than it should work

**Comment by jiahao** [comment]
Actually you can get paginated contributors using a different URL:

```
https://api.github.com/repos/JuliaLang/julia/contributors?page=2
```

It doesn't contain the weeks information but I don't think many people use that anyway. (I certainly don't need it for [World of Julia](https://github.com/jiahao/ijulia-notebooks/blob/master/2014-06-30-world-of-julia.ipynb).)

**Comment by WestleyArgentum** [comment]
Interesting, I'll try looking into that then

**Comment by WestleyArgentum** [comment]
Please have a look at that pull request and let me know if it works for you
